### ISSUE TITLE
feedback on sharePeers function

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#15]
comments on this function: https://github.com/WhoSoup/factom-p2p/blob/master/controller_cat.go#L104

1. `peer == nil` I am all for defensive coding, but this is the only function you adopt this strategy, is there a reason? Especially if you check the only place this is called, it's impossible for peer to be nil (otherwise it would have paniced earlier anyway). So for consistency, I'd say remove this check, or add it to all the other functions receiving a *Peer.
2. should `list` need to be an argument of the function? couldnt the signature just be `sharePeers(peer *Peer)` and then inside just
```
payload, err := peer.prot.MakePeerShare(c.makePeerShare(peer.Endpoint))
```
This would actually make your comment `// CAT select n random active peers` more accurate, because within just the context of this function you do no now that the list you have been passed is n randomly selected active peers, it could be anything.

**Comment by WhoSoup** [comment]
1. You're right, error check isn't needed. the managedata loop already does this, though i think that may also be redundant
https://github.com/WhoSoup/factom-p2p/blob/11a13ce3a9b5905223654997e1fdf30b8bf2d1ec/controller_routing.go#L36-L39

2. It's a preference thing for the most part. Doing it this way allows for changing the functionality (stuffing a different list into the function) in the future, as well as make it easier for unit testing. You're right that the comment is outdated, however
