### ISSUE TITLE
feedback on controller_peristence file

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#18]
Commenting on https://github.com/WhoSoup/factom-p2p/blob/master/controller_persistence.go

I don't think `Persist` is a really good name for the struct: 1. it's generic/abstract, it doesn't say anything of what is being persisted or for what purpose. 2. It's also a verb, that lead the creation of functions like `persistData` which, unexpectedly, doesn't persist any data :) I was thinking about `PeerSnapshot`, but feel free to propose something else. Also the `boostrap` field describe

**Comment by WhoSoup** [comment]
Renaming it to "PeerCache" and "Bootstrap" to "Peers"

**Comment by PaulBernier** [comment]
Oh right, cache is a great name.
