### ISSUE TITLE
Questions on controller#run

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#19]
Commenting on https://github.com/WhoSoup/factom-p2p/blob/master/controller_run.go#L9

What made you tie together sequentially those 3 functions (runCatRound, runMetrics, runPing) in the same event loop, while other functions got the right to get [their own go routines ](https://github.com/WhoSoup/factom-p2p/blob/master/controller.go#L210)? (I say sequentially, but it's not completely true as runMetrics actually spawns its own goroutine)

Also do you really need to constantly poll metrics? I don't see any hook yet, what did you have in mind? Why can't metrics be requested on demand only when necessary by calling makeMetrics()? I guess the answer depends on where/when you were thinking this will be used.

**Comment by WhoSoup** [comment]
I mentioned this in the other issue, but I wanted to drop peers before pinging/doing metrics. The functionality of each function on its own is so small that it seemed like a waste to dedicate an entire goroutine to it. 

The metrics is intended for integration with factomd, where the control panel currently expects metrics to arrive in the metrics channel every second. That's the only reason:
https://github.com/WhoSoup/factomd/blob/443f1f4ff39022db18eeae3525dbebc5a4785f90/engine/NetStart.go#L412-L417

**Comment by PaulBernier** [comment]
:ok_hand:
