### ISSUE TITLE
review of StartWithHandshake

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#22]
This one I have a mix of thoughts, suggestions and questions: https://github.com/WhoSoup/factom-p2p/blob/master/peer.go#L121

1. From a OO design point of view I am not sure `StartWithHandshake` should be a method of Peer, it feels to me that this is the method that should give birth to a fully functional Peer. Right now `newPeer` creates a shallow, non-functional peer, that is then immediately modified by side effects within this function to become, or not, a valid peer. I personally prefer when instances are created in a complete consistent state. Right now, depending on the exit point  of StartWithHandshake, you may end up with a Peer instance with 3 different states of populated fields, I think that has potential for confusion and inconsistencies. Maybe Handshake handling should just be a method of the controller.

2. I am not sure I understand completely the `incoming` concept. I get it it distinguish the case when our node Dials (incoming = false) vs another node dial us (incoming = true), but that distinction is only necessary at the time of the handshake, so why it is persisted in Peer object afterwards? Once a new peer is added, the relation between the 2 becomes completely symmetrical, regardless of who initiated the connection, isn't it? Also in the case `incoming = true`, what happens to `decoder.Decode(&reply)`? Is a response really expected even though it was already the other node that initiated the connection? 

3. You test `reply.Header.Type` for `TypeRejectAlternative`, should you go further and test that this header type is not an unexpected type during a handshake? Going even further, check that you get an `TypeRejectAlternative` solely in case of `incoming = false`? Basically I would tighten the validation around `reply.Header.Type` to definitely rule out potential inconsistent states.

4. I am confuse by `ep.Port = reply.Header.PeerPort`. We have established a TCP connection with a given IP and port already, what does this PeerPort returned mean and why does it override the real port?

5. is `registered` attribute really necessary? Wouldn't it be safer to handle the status of a Peer in a single place? When having 2 different data representing the same state, you may have consistency issues, so preferably if you can maintain this info in a single place it's better.

6. In `bootstrapProtocol` should you delete this `hsParcel` code or are you expecting to still use it later?

7. Should banned endpoints be handled as part of the Handshake? [Right now](https://github.com/WhoSoup/factom-p2p/blob/master/controller_connections.go#L103) we go through a handshake that is meant to say "we can do business together" and then immediately after drop the peer without explanation, kind of rude! :)

8. [not Handshake related be in the same file] in  `statLoop` that 5 should really be a variable :)

**Comment by WhoSoup** [comment]
> 1. From a OO design point of view I am not sure `StartWithHandshake` should be a method of Peer, it feels to me that this is the method that should give birth to a fully functional Peer.

That's an interesting suggestion. The peer lifecycle is based on the peer from p2p1, which definitely made a distinction between "offline peers" and "online peers" (you'll see more of this in the upcoming bullet points). CAT changed that lifecycle and startwithhandshake is now always called immediately after making a new peer, so it makes sense to initiate the peer directly.

I think the Handshake code could be in either Peer or Controller. I went with Peer because the handshake deals with picking the protocol (which is a child of peer) and the gob encoders (also a child of peer). 

I'm open to suggestions if you have them.

Sidenote: Golang isn't OO. The function `func (p *Peer) Foo()` is mostly just syntactic sugar for the function `func Foo(p *Peer)` with the upsides of allowing function overloading.

**Comment by WhoSoup** [comment]
> 2\. I am not sure I understand completely the `incoming` concept. I get it it distinguish the case when our node Dials (incoming = false) vs another node dial us (incoming = true), but that distinction is only necessary at the time of the handshake, so why it is persisted in Peer object afterwards? Once a new peer is added, the relation between the 2 becomes completely symmetrical, regardless of who initiated the connection, isn't it?

That's a leftover from p2p1, which differentiated between incoming and outgoing connections. It had different limits for incoming vs outgoing and would stop dialing at some point but still accept inbound connections to a much higher limit. Right now, factomd dials until it has 32 connections but accepts incoming connections until 200. 

Right now it still exists to keep track of stats in Prometheus:
https://github.com/WhoSoup/factom-p2p/blob/2f77f66a3cfd43ae76fffc014dba827ce0d67d9f/controller_connections.go#L39-L40

> Also in the case `incoming = true`, what happens to `decoder.Decode(&reply)`? Is a response really expected even though it was already the other node that initiated the connection?

The handshake is symmetrical, so in this case the order is important. Both sides will send their handshake first, then read the first incoming parcel. The response is definitely expected.

**Comment by WhoSoup** [comment]
> 3\. You test `reply.Header.Type` for `TypeRejectAlternative`, should you go further and test that this header type is not an unexpected type during a handshake? Going even further, check that you get an `TypeRejectAlternative` solely in case of `incoming = false`? Basically I would tighten the validation around `reply.Header.Type` to definitely rule out potential inconsistent states.

In this case, error checking doesn't really have any benefits I can think of.

The handshake is built on the behavior of old nodes which do not have a handshake procedure at all. What they do is immediately send a "TypePeerRequest" parcel after connecting. V10 sends out a TypeHandshake parcel which are ignored by old nodes (without errors). This makes the entire process very malleable when it comes to parcel type, as the only requirement is that the very first parcel is a V9 Parcel. The fact that it decodes into a valid V9 parcel is already a type check, but theoretically any valid V9 Parcel will contain the necessary info.

The only special case is TypeRejectAlternative.

**Comment by WhoSoup** [comment]
> 4\. I am confuse by `ep.Port = reply.Header.PeerPort`. We have established a TCP connection with a given IP and port already, what does this PeerPort returned mean and why does it override the real port?

The TCP connection port is a randomly assigned local port on our machine. The PeerPort in the parcel is the port that the other node is configured to listen for new connections at (ie 8108 or 8110).

Edit: For incoming connections, we assume the default port is the same as the network's own listening port, not the local tcp port. For outgoing connections, the remote port is already known.

**Comment by WhoSoup** [comment]
> 5\. is `registered` attribute really necessary? Wouldn't it be safer to handle the status of a Peer in a single place? When having 2 different data representing the same state, you may have consistency issues, so preferably if you can maintain this info in a single place it's better.

It's not the status of the peer, but rather the status of whether or not the peer has registered with the PeerStore, which is used to not send an unnecessary signal the to PeerStore when stopping a peer that failed to connect. This happens here:
https://github.com/WhoSoup/factom-p2p/blob/2f77f66a3cfd43ae76fffc014dba827ce0d67d9f/controller_connections.go#L97

If you have a better suggestion of handling it, please let me know. (Moving the handshake code to the controller would be one way, I think)

**Comment by WhoSoup** [comment]
> 6\. In `bootstrapProtocol` should you delete this `hsParcel` code or are you expecting to still use it later?

As I mentioned before, V9 sends a PeerRequest upon connecting, so it expects a PeerResponse. My idea was to mimic the behavior of the old nodes and tell the controller the peer received a PeerRequest, but doing it in that spot introduced a race condition where the controller could try to respond before the peer finished initializing and crash. 

I'm probably going to remove the code. That will cause old nodes to send another PeerRequest after the first one timed out, which is fine since that code is going to be deprecated anyway.

**Comment by WhoSoup** [comment]
> 7\. Should banned endpoints be handled as part of the Handshake? [Right now](https://github.com/WhoSoup/factom-p2p/blob/master/controller_connections.go#L103) we go through a handshake that is meant to say "we can do business together" and then immediately after drop the peer without explanation, kind of rude! :)

For inbound connections, there are two ban-checks. One happens in [allowIncoming()](https://github.com/WhoSoup/factom-p2p/blob/2f77f66a3cfd43ae76fffc014dba827ce0d67d9f/controller_connections.go#L48), which checks whether or not the ip address is banned and doesn't start the handshake process. However, at that point we don't have the full Endpoint yet. It's only after the handshake is complete that we know the ip:listenport of the other node. 

So regardless of how we implement it, the handshake has to happen before we know if we are supposed to ban them. The check could definitely happen earlier (before the peer loops are even started), which makes more sense if the handshake is part of the controller.

**Comment by WhoSoup** [comment]
> 8\. [not Handshake related be in the same file] in  `statLoop` that 5 should really be a variable :)

Yeah, it should be, just haven't found the right place for it. Do you think it would be worthy enough of a Configuration variable? Something like:

`BandwidthMetricsInterval time.Duration // controls how finely to measure bandwidth. lower values may be more inaccurate for spiky traffic`

**Comment by WhoSoup** [comment]
One thing I noticed, particularly with 5 and 7 that there is a lot of argument for moving the Handshake code to the controller. That would mean a Peer is initialized with a fully fledged Metrics / Protocol instance and finalized Endpoint, all it has to do is start the loops. It never has to be aware of the connection at all. 

It's going to require shifting a bunch of stuff around (like metrics), I'll try it out and see how well it works.

**Comment by PaulBernier** [comment]
Thanks for all the explanations it's much clearer. I think most of my confusions came from 2 facts:

- I completely overlooked the fact that this handshake was built in a way to be backward compatible with V9 protocol which doesn't even have a handshake, that defintly change my reading of the function.
- the same method handle both incoming and outgoing cases which have their specificities which I did,'t always have in mind.

So in the end the challenge for me was that there is this unified function handling 4 cases in one flow (v9, v10, incoming, outgoing) which can be quite hard to mentally process when reading the code. Looking at the refactor PR it does seem to make it much clearer though, I think I am just going to advise to add one or two comments in the PR to help the comprehension, otherwise I am good.
