### ISSUE TITLE
should MetricsReadWriter rather use atomic counters?

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#24]
Collect and Read/Write set counter values in different goroutines, so I believe they should use atomic counters? https://gobyexample.com/atomic-counters

**Comment by PaulBernier** [comment]
On a side node, have you tried to run a simulation app (https://github.com/WhoSoup/factom-test-network ?) with the race condition detector on? (`-race`) It's a pretty neat feature, it may feel overwhelming at first but it's pretty smart and useful, even if you don't intend to fix all the complaints.

**Comment by WhoSoup** [comment]
> Collect and Read/Write set counter values in different goroutines, so I believe they should use atomic counters? https://gobyexample.com/atomic-counters

I originally wanted to avoid a mutex here since the read/write operations can take significant amounts of time and it would block the stats routine and make that logic more difficult but I think you're right, there's a case where read/write could potentially overwrite the reset in collect.

**Comment by WhoSoup** [comment]
> On a side node, have you tried to run a simulation app (https://github.com/WhoSoup/factom-test-network ?) with the race condition detector on?

Not yet but I'll check it out when I have time

**Comment by WhoSoup** [comment]
Ended up taking a look at the race tester and there were a couple of oddities. more in #37
