### ISSUE TITLE
makePeerShare can return longer that expected Endpoint slice

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#3]
This condition doesn't depend on any variable being changed in the loop: https://github.com/WhoSoup/factom-p2p/blob/master/controller_cat.go#L96 which makes it suspicious to me.
I think what you wanted to do is break if `list` is long enough, instead of the condition being on `tmp`?

Unrelated but in the same function:

- I don't think you need to declare `i` outside of the loop, it should just be defined at the loop scope.
- Maybe rename `tmp` to `peers`?

**Comment by WhoSoup** [comment]
Great catch, it should indeed be a check on the other slice. I also cleaned up the code to address the other comments, as well as renamed the parameter to be more precise
