### ISSUE TITLE
Mixed file naming convention?

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#31]
What is your file naming convention? 
I see you have `controller`, `controller_cat`, `controller_run`...
but also `parcel`, `parcelType`, `parcelChannel`...

**Comment by WhoSoup** [comment]
The controller.go file was getting too large, so I just split it into multiple files by adding `_subcategory`. It's all still part of the "controller" entity, if that makes sense. Sort of like how `controller_test` indicates the file contains test functions related to controller. 

I suppose the convention is: `nameOfEntity_nameOfFunctionGroup`

**Comment by PaulBernier** [comment]
I was just raising an eye brow at the mix of camel case and snake case, but it seems like there is no general guideline for a file naming convention in Go, so that's fine I guess.
