### ISSUE TITLE
trimShare does more than trimming

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#5]
https://github.com/WhoSoup/factom-p2p/blob/master/controller_cat.go#L72
2 minor comments about that function:

- it is used solely with `shuffle` boolean being true. If there is no use case for not shuffling, do you really need that parametrization? 
- the function is called `trimShare` but also shuffle. And because the shuffle is enabled by a boolean, it's hard to guess from just reading the client call what that boolean means (because the function name says nothing about its potential meaning)

Given the comments above, maybe rename the function `trimShuffleShare` without a `shuffle` parameter?

**Comment by WhoSoup** [comment]
I went with shuffleTrimShare since that's the order
