### ISSUE TITLE
Use bytes.Equal to compate byte slices

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#8]
https://github.com/WhoSoup/factom-p2p/blob/master/peer.go#L161
https://golang.org/pkg/bytes/#Equal

Can you also explain me when the loopback case may happen?

**Comment by WhoSoup** [comment]
The byte sequences were created as strings, so the comparison between the strings is okay, but I agree it's not clean code. Addressing this in a PR to consistently use bytes throughout.

A loopback happens during the handshake to detect a node connecting to itself. A random instanceID is generated when a new Network is initialized:
https://github.com/WhoSoup/factom-p2p/blob/11a13ce3a9b5905223654997e1fdf30b8bf2d1ec/network.go#L56

This instanceID is sent as the Payload of the handshake message. If the "other" node also sends a handshake with the same instanceID, it returns a loopback error.
